services:
  nginx:
    container_name: srm-nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8075:80"
    networks:
      - srm_internal
    volumes:
      - ../app/backend/public/:/var/www/html
      - ../docker/nginx/logs:/var/log/nginx
    depends_on:
      - php
    restart: always
  php:
    container_name: srm-php
    privileged: true
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    networks:
      - srm_internal
    ports:
      - "4000:4000"
    volumes:
      - ../app/backend/:/var/www/html
      - vendor:/var/www/html/vendor
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:192.168.1.252"
    restart: always
  mailhog:
    container_name: srm-mailer
    image: mailhog/mailhog
    networks:
      - srm_internal
    ports:
      - 1025
      - "8027:8025"
    restart: on-failure
  db:
    container_name: srm-db
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_NAME:-deployments}"
      MYSQL_USER: "${DB_USER:-deploy_user}"
      MYSQL_PASSWORD: "${DB_PASS:-pass}"
      TZ: "${APP_TIMEZONE:-Europe/London}"
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - mysql-phpmyadmin
      - srm_internal
    restart: always
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: srm-phpmyadmin
    environment:
      PMA_HOST: "${DB_HOST:-db}"
      PMA_PORT: "${DB_PORT:-3306}:3306"
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8083:80"
    networks:
      - mysql-phpmyadmin
      - srm_internal
    restart: always

volumes:
  db_data:
  vendor:
    driver: local
networks:
  mysql-phpmyadmin:
  srm_internal:
    driver: bridge
    name: srm_internal
